### ISSUE TITLE
laravel-zero.com is inaccessible

### ISSUE THREAD

**Issue by JuhaniGeniem** [laravel-zero/laravel-zero#360] opened 2021-11-10 12:42 UTC
The website is nowhere to be found.

**Comment by owenvoke** [comment] 2021-11-10 12:44
Please look over at #359 👍🏻 It's known by Nuno and is being resolved.

**Comment by wpoortman** [comment] 2021-11-12 07:29
> Please look over at #359 👍🏻 It's known by Nuno and is being resolved.

The issue is already closed but the website is still down.

**Comment by owenvoke** [comment] 2021-11-14 12:08
Looks like it's now [back up again](https://laravel-zero.com), so closing this issue. Thanks. 👍🏻

**Closed by owenvoke** 2021-11-14 12:08 UTC
