### ISSUE TITLE
Remove unnecessary files when build

### ISSUE THREAD

**Issue by rookie0** [laravel-zero/laravel-zero#54] opened 2017-09-05 02:06 UTC
It's size is 8M after build(empty project).
Although storage space is negligible in this day and age.
But i still think the smaller the better, and what do u think?

**Comment by nunomaduro** [comment] 2017-09-05 05:59
I totally understand your point of you view @rookie0. Today the build command is taking the following structure:

```
        'app/',
        'bootstrap/',
        'vendor/',
        'config/',
```

> It's size is 8M after build(empty project).

The problem is the vendor folder, that after a `composer install` he becomes quite full. Do you have any sugestion?

**Comment by rookie0** [comment] 2017-09-05 06:16
I am think about based on composer autoload(classmap files psr4 etc.) to add necessary files and dirs to phar archive.

Is it feasible?

**Comment by nunomaduro** [comment] 2017-09-05 11:30
@rookie0 Thanks for the suggestion! I will investigate this proposal and give you feedback after!

**Comment by ashleyhood** [comment] 2017-09-05 13:58
It would be better to create a list of common directories to exclude from each vendor directory (e.g. vendor/laravel-zero/framework/tests/).  The composer classmap will not tell you how to include things like binary files, images or text files etc.

It could help to look at [box2](https://github.com/box-project/box2) and how they do it.  They have an array of directories and files to include and also use Symfony\\Component\\Finder\\Finder to filter the vendors directory.

**Comment by nunomaduro** [comment] 2017-09-08 18:49
Thanks! I will take a look!

**Comment by ashleyhood** [comment] 2017-12-20 12:58
I have reduced the built phar by about 1/3 the size by excluding *tests* directories and only including files ending with *.php* within the vendors directory.

In my `config/app.php`:

    'structure' => [
        'app'.DIRECTORY_SEPARATOR,
        'bootstrap'.DIRECTORY_SEPARATOR,
        'vendor'.DIRECTORY_SEPARATOR.'(?!(.*tests)).*\.php$',
        'config'.DIRECTORY_SEPARATOR,
        'composer.json'
    ],

Also you will greatly reduce phar size by not installing require-dev packages:

    composer install --no-dev

What do you think about running `composer install --no-dev` as part of the `app:build` command?

**Comment by nunomaduro** [comment] 2017-12-22 22:06
Concerning the `exclude non .php` thing, I believe that is super risky, since some packages may depend of some .json or .ini files.

Concerning the `composer install --no-dev`, could be interesting, but currently the build is based on the current installation of the application.

To be completely honest with you - I am waiting the some package, like `box2`, to re-make this build feature.

**Comment by nunomaduro** [comment] 2018-02-18 21:40
I am going to close this issue, the conversation seems dead.

**Closed by nunomaduro** 2018-02-18 21:40 UTC
Labels: enhancement

**Comment by nunomaduro** [comment] 2018-03-03 22:15
The `build` feature just got a big improvement. The compiled file takes up 50% less space than before! https://github.com/laravel-zero/framework/pull/211

**Comment by sergiz** [comment] 2020-03-26 21:21
I was just thinking, why pretty bare laravel-zero compiles to around 5MB, while for example composer is only 1.9MB?

**Comment by nunomaduro** [comment] 2020-03-27 00:13
The Laravel Zero's vendor is bigger than composer's vendor.

**Comment by mikeerickson** [comment] 2020-03-27 00:21
5mb is small folks!
