### ISSUE TITLE
Unable to build app when certain dependencies are installed

### ISSUE THREAD

**Issue by juanparati** [laravel-zero/laravel-zero#334] opened 2021-02-19 14:34 UTC
I am running in very weird issue. It seems that when certain dependencies are installed the following error is raised:

```
 ErrorException

rename(/Users/juan/Projects/tmp/movie-cli/application.phar,/Users/juan/Projects/tmp/movie-cli/builds/application): No such file or directory
```

Steps to reproduce:
1. `composer create-project --prefer-dist laravel-zero/laravel-zero movie-cli`
2. ` cd movie-cli`
3. `composer require google/cloud-bigquery`
4. `./application app:build`

In this case the application cannot be compiled when "google/cloud-bigquery" dependency was installed.

It seems that following error is raised in verbose mode:

In StandardTagFactory.php line 86:
                                                                               
```
  The tag "@ depends testParseTemplateWithLiteral" does not seem to be wellfo  
  rmed, please check it for errors                                             
                                                                               

compile [-c|--config CONFIG] [--debug] [--no-parallel] [--no-restart] [--dev] [--no-config] [--with-docker] [-d|--working-dir WORKING-DIR]
```

It was tested in Mac OS and Ubuntu (Homestead) with PHP 7.3 and 8.0.

Laravel-zero 8.6.0 and 8.5.0 was used.

If remove the dependency everything works as expected.

**Comment by juanparati** [comment] 2021-02-19 14:37
It also fails when "NONE" is used as compressor.

**Comment by owenvoke** [comment] 2021-02-19 14:48
It looks like that's caused by a dependency of `google/cloud-core` called `rize/uri-template` ([`ParserTest#L111`](https://github.com/rize/UriTemplate/blob/master/test/Rize/Uri/Node/ParserTest.php#L111) and [`ParserTest#L122`](https://github.com/rize/UriTemplate/blob/master/test/Rize/Uri/Node/ParserTest.php#L122)).

The `@depends` tag is invalid in the test and this is getting parsed by the Box compactors. You could try opening a PR on that repository to resolve the issue by either removing the spaces in those tags, or adding a `.gitattributes` that ignores the `test/` directory. Or disable the PHP compactor in your `box.json` to see if that resolves the issue. Alternatively, it may be easiest to ignore the `tests/` directory under that package in your vendor directory.

**Comment by juanparati** [comment] 2021-02-19 14:55
@owenvoke Yes I was researching about the issue I reach the same conclusion.

I deleted the files located at "rize/uri-template/tests" and and now it works as a temporal workaround.

I think that this issue is not easy to fix because laravel-zero depends on the Laravel filesystem libs that uses rize/uri-template.

**Comment by owenvoke** [comment] 2021-02-22 13:08
I don't think `rize/uri-template` is used by Laravel Zero by default. 🤔 But anyway, I've created two PRs on that package (https://github.com/rize/UriTemplate/pull/17 and https://github.com/rize/UriTemplate/pull/18) that combined should resolve this issue. 👍🏻

**Comment by owenvoke** [comment] 2021-02-22 15:52
@juanparati, could you try updating to `v0.3.3` of the `rize/uri-template` package? (A `composer update` should do this). 👍🏻 And then let me know if the build is working now.

**Comment by acrossoffwest** [comment] 2021-03-09 10:13
@juanparati do you have installed php extension intl? Try install it. It fixed my issue as well

**Comment by owenvoke** [comment] 2021-03-26 12:26
Closing as this should be resolved. Please let me know if not.

**Closed by owenvoke** 2021-03-26 12:26 UTC
